# Generated by Django 3.2.16 on 2023-02-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_author_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('name', 'price')},
        ),
    ]
