# Generated by Django 3.2.16 on 2023-02-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_book_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('name', 'price', 'rating')},
        ),
    ]
