# Generated by Django 4.1.6 on 2023-02-15 00:02

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 15, 0, 2, 48, 435886, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
