# Generated by Django 4.1.6 on 2023-02-22 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(help_text='Author bio', max_length=1000)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.author')),
            ],
        ),
    ]
