# Generated by Django 4.1.6 on 2023-02-21 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_author_age_alter_author_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='quote',
            new_name='text',
        ),
    ]
