# Generated by Django 4.1.6 on 2023-02-22 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_authorprofile'),
        ('crm', '0010_rename_quote_quotes_text'),
    ]

    operations = [
    ]
