# Generated by Django 4.1.5 on 2023-01-30 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_author_bio_alter_book_publisher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
