# Generated by Django 3.2.16 on 2023-02-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_requestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='status_code',
            field=models.IntegerField(null=True),
        ),
    ]
