# Generated by Django 3.2.16 on 2023-02-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_requestlog_status_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestlog',
            old_name='author',
            new_name='full_response',
        ),
    ]
