# Generated by Django 3.2.16 on 2023-02-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_rename_author_requestlog_full_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, verbose_name='IP address from request'),
        ),
    ]
