# Generated by Django 3.2.16 on 2023-02-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='body_unicode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
